name: Deploy

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Install dependencies and run linter
              run: |
                  npm ci
                  npm run lint

    deploy:
        needs: lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Build and Package Application
              run: |
                  npm ci
                  npm run build
                  tar czf ../app.tar.gz -C dist .

            - name: Copy Package to VPS
              env:
                  HOST: ${{ secrets.VPS_HOST }}
                  USER: ${{ secrets.VPS_USER }}
                  SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
              run: |
                  echo "$SSH_KEY" > ssh_key
                  chmod 600 ssh_key

                  scp -i ssh_key -o StrictHostKeyChecking=no ../app.tar.gz $USER@$HOST:~/spottmee/tars/

            - name: Deploy on VPS
              env:
                  HOST: ${{ secrets.VPS_HOST }}
                  USER: ${{ secrets.VPS_USER }}
                  SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
              run: |
                  echo "$SSH_KEY" > ssh_key
                  chmod 600 ssh_key

                  ssh -i ssh_key -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
                    set -e
                    cd ~/spottmee/tars

                    # Extract package
                    mkdir -p spottmee-app
                    tar xzf app.tar.gz -C spottmee-app --strip-components=1
                    cd spottmee-app

                    # Ensure swap is enabled
                    if ! sudo swapon --show | grep -q '/var/swap.1'; then
                      sudo fallocate -l 1G /var/swap.1 || sudo dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
                      sudo chmod 600 /var/swap.1
                      sudo mkswap /var/swap.1
                      sudo swapon /var/swap.1
                    fi

                    # Copy built files to /var/www/spottmee.com/ replacing the old ones
                    sudo rm -rf /var/www/spottmee.com/*
                    sudo cp -r ./* /var/www/spottmee.com/
                  EOF
